services:
  db:
    container_name: ft_postgres
    env_file:
      - .env
    restart: always
    image: postgres:16.1
    volumes:
      - ft_postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    container_name: ft_api
    expose:
      - ${BACKEND_API_PORT}
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    restart: always
    build: ./backend
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - ${BACKEND_API_PORT}:${BACKEND_API_PORT}
    command: yarn start:dev

  frontend:
    container_name: ft_front
    depends_on:
      api:
        condition: service_started
    env_file:
      - .env
    environment:
      - PORT=${FRONTEND_WEBAPP_PORT}
      - HOSTNAME=${FRONTEND_WEBAPP_HOSTNAME}
    restart: always
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports: 
      - ${FRONTEND_WEBAPP_PORT}:${FRONTEND_WEBAPP_PORT}
    command: yarn run dev
 
volumes:
  ft_postgres_data:
  